name: Build and Release iOS App

on:
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Xcode
        run: |
          sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

      - name: List directory contents
        run: |
          ls -R ${{ github.workspace }}

      - name: Build the iOS app
        run: |
          xcodebuild -project iMemScan.xcodeproj -scheme iMemScan -configuration Release -archivePath ${{ github.workspace }}/build/iMemScan.xcarchive archive
          xcodebuild -exportArchive -archivePath ${{ github.workspace }}/build/iMemScan.xcarchive -exportOptionsPlist exportOptions.plist -exportPath ${{ github.workspace }}/build

      - name: Upload IPA to release
        uses: actions/upload-artifact@v3
        with:
          name: iMemScan.ipa
          path: ${{ github.workspace }}/build/iMemScan.ipa

      - name: Create a GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          body: |
            ## New Release
            This release contains the latest version of the iMemScan app.
          files: |
            ${{ github.workspace }}/build/iMemScan.ipa
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
